/*
 * Selects the vmlinux.h matching the architecture bpf2go is compiling for.
 *
 * The kernel type definitions differ per architecture -- most importantly
 * struct pt_regs, whose members the PT_REGS_PARM* macros in bpf_tracing.h
 * expand to. Compiling the x86 target against an arm64 vmlinux.h fails with
 * "no member named 'di' in 'struct pt_regs'", so each target needs its own.
 *
 * bpf2go defines __TARGET_ARCH_<arch> for every entry in its -target list.
 * The headers themselves are generated by the Makefile from the BTF blobs
 * vendored under bpf/btf/, so they are not checked in.
 */

#ifndef VEIL_TARGET_ARCH_H
#define VEIL_TARGET_ARCH_H

#if defined(__TARGET_ARCH_x86)
#include "vmlinux_x86.h"
#elif defined(__TARGET_ARCH_arm64)
#include "vmlinux_arm64.h"
#else
#error "no __TARGET_ARCH_* defined: bpf2go needs -target amd64,arm64"
#endif

#endif /* VEIL_TARGET_ARCH_H */
