package syscall

//go:generate bpf2go -cc clang -cflags "-O2 -g -Wall -target bpf" Tracer ../../bpf/syscall_tracer.bpf.c
//go:generate go run ../../cmd/gen/syscalls

/*
	********************************** NOTE **********************************

	This file relies on the existence of the ELF file that is generated via Go's
	generate subcommand. Furthermore, the second line generates the
	syscall_table.go file which is used by the CLI application. The LoadAll()
	method of BaseProgram structure internally calls the Load() method for that
	type. We define it here. Likewise, Close() method for CloseAll() method of
	BaseProgram is defined here. Do note that since we embed the BaseProgram
	structure in TracerModule, it will be compatible.

	The New() method for TracerModule object is used to allocate the storage
	which is done so by the runtime, and the poll() method is used to poll
	the goroutine till we can read from the channel. The userspace client
	applies filter to the command name (the process name executing the traced
	syscall) whereas the bpf program is responsible for filtering out based
	on PID, UID, or syscall number.

	Other non-trivial remarks can be seen in the program source below.

	********************************** NOTE **********************************
*/

import (
	"fmt"
	"strconv"
	"strings"

	"github.com/cilium/ebpf"
	"github.com/cilium/ebpf/link"
	"github.com/cilium/ebpf/ringbuf"
	"github.com/PranavRJoshi/Veil/internal/exterrs"
	"github.com/PranavRJoshi/Veil/internal/events"
	"github.com/PranavRJoshi/Veil/internal/loader"
	"github.com/PranavRJoshi/Veil/internal/output"
	"github.com/PranavRJoshi/Veil/internal/registry"
)

/*
	NOTE: The init function in Go is a special function. When
	used in packages and imported by other files, it will
	be loaded before the startup function, i.e., main will be
	executed. Do note that it is executed after the global variables
	have been initialized.
*/
func init() {
	registry.Register(registry.ModuleInfo{
		Name:        "syscall",
		Description: "Trace system call events (raw_syscalls:sys_enter)",
		Flags: []registry.FlagDef{
			{Name: "pid", Short: "p", Description: "Filter by PID (comma-separated)", HasValue: true},
			{Name: "uid", Short: "u", Description: "Filter by UID (comma-separated)", HasValue: true},
			{Name: "name", Short: "n", Description: "Filter by process name (comm)", HasValue: true},
			{Name: "syscall", Short: "s", Description: "Filter by syscall name (comma-separated)", HasValue: true},
		},
		Factory: func(flags map[string]string, sinkIface interface{}) (interface{}, error) {
			sink, ok := sinkIface.(output.EventSink)
			if !ok {
				return nil, fmt.Errorf("syscall: expected output.EventSink, got %T", sinkIface)
			}
			filter, err := ParseFilterConfig(flags)
			if err != nil {
				return nil, err
			}
			return New(filter, sink), nil
		},
	})	
}

/*
	FilterConfig holds the parsed filter values from the CLI flags.
	These are used to populate BPF filter maps after loading the
	BPF objects. Userspace filters (comm name, syscall name) are
	applied in the poll loop since they require string matching.
*/
type FilterConfig struct {
	PIDs     []uint32   /* -p flag: filter by PID */
	UIDs     []uint32   /* -u flag: filter by UID */
	Syscalls []string   /* -s flag: filter by syscall name(s) */
	CommName string     /* -n flag: filter by process name (userspace) */
}

/*
	ParseFilterConfig interprets the raw CLI flags map into a typed
	FilterConfig. Returns an error for invalid values (e.g. non-numeric PID).
*/
func ParseFilterConfig(flags map[string]string) (FilterConfig, error) {
	var cfg FilterConfig
 
	if raw, ok := flags["pid"]; ok {
		/* comma separated list is only supported */
		for _, s := range strings.Split(raw, ",") {
			v, err := strconv.ParseUint(strings.TrimSpace(s), 10, 32)
			if err != nil {
				return cfg, fmt.Errorf("invalid PID %q: %w", s, err)
			}
			cfg.PIDs = append(cfg.PIDs, uint32(v))
		}
	}
 
	if raw, ok := flags["uid"]; ok {
		/* comma separated list is only supported */
		for _, s := range strings.Split(raw, ",") {
			v, err := strconv.ParseUint(strings.TrimSpace(s), 10, 32)
			if err != nil {
				return cfg, fmt.Errorf("invalid UID %q: %w", s, err)
			}
			cfg.UIDs = append(cfg.UIDs, uint32(v))
		}
	}
 
	if raw, ok := flags["syscall"]; ok {
		for _, s := range strings.Split(raw, ",") {
			cfg.Syscalls = append(cfg.Syscalls, strings.TrimSpace(s))
		}
	}
 
	if raw, ok := flags["name"]; ok {
		cfg.CommName = raw
	}
 
	return cfg, nil
}

/*
	A type which is compatible with the Program interface, hence the Manager type
	can contain multiple instances of this type, if ever needed.

	Both the Name() and State() methods of loader.BaseProgram are pointer receiver,
	so embedding the structure with value alone would not suffice as these methods
	would not be "promoted".
*/
type TracerModule struct {
	*loader.BaseProgram				/* embedding the BaseProgram */
	objs   TracerObjects			/* generated by bpf2go, holds maps and programs */
	link   link.Link				/* the tracepoint attachment */
	reader *ringbuf.Reader			/* reads events from the ring buffer */
	Events chan events.SyscallEvent	/* userspace consumes from this channel */
	filter FilterConfig				/* parsed filter configuration */
	sink   output.EventSink			/* output sink for formatted event emission */
}

/*
	Function which is essentially an allocator of TracerModule.
	Accepts a FilterConfig to configure kernel-side and userspace filtering,
	and an EventSink to decouple output formatting from the module.
*/
func New(filter FilterConfig, sink output.EventSink) *TracerModule {
	return &TracerModule{
		BaseProgram: loader.NewBaseProgram("syscall_tracer"),
		Events:      make(chan events.SyscallEvent, 256),
		filter:      filter,
		sink:        sink,
	}
}

/*
	populateFilters writes the filter values into the BPF maps after
	the objects have been loaded. It also sets the filter_cfg bitmask
	to indicate which filters are active.
 
	The bitmask convention matches the BPF C code:
	  bit 0 = pid_filter active
	  bit 1 = uid_filter active
	  bit 2 = syscall_filter active
*/
func (t *TracerModule) populateFilters() error {
	var mask uint32
	enable := uint8(1)

	/*
		The data type TracerObjects embeds TracerPrograms and TracerMaps.
		TracerMaps defines the fields such as PidFilter, UidFilter, SyscallFilter,
		and a couple more fields. The data type of these fields are ebpf.Map.
		This data type is defined in cilium/ebpf/map.go file. Under the same file,
		the method Update is defined, which is shown in the link below:
			- https://github.com/cilium/ebpf/blob/main/map.go#L1030-L1042C2

		The mask variable is used to keep track of the filters that should be applied
		and is used for filter_cfg map that we defined in bpf program file. For PIDs,
		UIDs, and syscall filters, we simply extract the value from the array and
		Update the map.

		TODO: The bpf program has a compile time constant for the length of hash map
		used for PID, UID, and Syscall number. Those numbers are sufficient for most
		usual execution, but it'd be better if the program here is also able to take
		that fact into account.
	*/
 
	/* Populate PID filter map */
	if len(t.filter.PIDs) > 0 {
		mask |= 1
		for _, pid := range t.filter.PIDs {
			if err := t.objs.PidFilter.Update(pid, enable, ebpf.UpdateAny); err != nil {
				return fmt.Errorf("syscall: set pid filter %d: %w", pid, err)
			}
		}
	}
 
	/* Populate UID filter map */
	if len(t.filter.UIDs) > 0 {
		mask |= 2
		for _, uid := range t.filter.UIDs {
			if err := t.objs.UidFilter.Update(uid, enable, ebpf.UpdateAny); err != nil {
				return fmt.Errorf("syscall: set uid filter %d: %w", uid, err)
			}
		}
	}
 
	/* Populate syscall number filter map: resolve names to numbers */
	if len(t.filter.Syscalls) > 0 {			/* check if the user specified particular syscall */
		mask |= 4
		for _, name := range t.filter.Syscalls {
			nr, ok := SyscallNumber(name)	/* defined in syscall_table.go */
			if !ok {
				return fmt.Errorf("syscall: unknown syscall name %q", name)
			}
			if err := t.objs.SyscallFilter.Update(nr, enable, ebpf.UpdateAny); err != nil {
				return fmt.Errorf("syscall: set syscall filter %q (%d): %w", name, nr, err)
			}
		}
	}
 
	/* Write the bitmask to filter_cfg[0] */
	if mask != 0 {
		cfgKey := uint32(0)
		if err := t.objs.FilterCfg.Update(cfgKey, mask, ebpf.UpdateAny); err != nil {
			return fmt.Errorf("syscall: set filter config: %w", err)
		}
	}
 
	return nil
}

/*
	Load() method, which is required for our Program interface.
	Note that each invocation of this function spawns a goroutine which is used
	to poll for any message written by BPF program in kernel space.
*/
func (t *TracerModule) Load() error {
	/*
		See LoadAndAssign() method of CollectionSpec for complete details.
		
		This function initially calls LoadTracer function. A new reader is
		obtained via the Reader functions defined in the bytes package.
		Next, LoadCollectionSpecFromReader from ebpf package is called with
		the Reader structure as the argument which was previously obtained. 
		This function is defined in cilium/ebpf/elf_reader.go file. The main
		functionality of this function is to convert the ELF file into
		an object of type CollectionSpec.

		One thing before moving on. The LoadCollectionSpecFromReader function
		also calls NewSafeELFFile function defined in cilium/ebpf/internal/elf.go
		file. This file imports debug/elf module which seems to contain "unfixed
		bugs", so a safe alternative needs to be implemented. Be aware that the
		safe implementation is the addition of a defer statement at the start of
		the function, where the recover() function is called. The functions: panic(),
		recover(), and defer(), are used to handle runtime errors in a gentle
		manner. By having the defer() function at the start which has the recover()
		function within it, if an error was to occur during parsing of ELF file,
		the goroutine would panic, and as libraries need to handle panics such that
		application using the library shouldn't get the panic from internal
		implementation of library, it simply catches the reason of panic through
		recover(), and returns appropriate failure condition. When no abnormal
		condition appears, recover() is simply nil and the flow is maintained.

		Finally, LoadAndAssign() method of CollectionSpec is called. This method
		is used to load maps and programs into the kernel and assigns them to
		a struct. Refer to cilium/ebpf/collection.go for actual implementation
		details. Do note that this method also internally uses the "reflection"
		concept, which is why the bpf2go generated file's structure's fields
		contains "structure tags" in them. Rob Pike has a blog post in regards
		to "The Laws of Reflection" which can be found at the link below:
			- https://go.dev/blog/laws-of-reflection

		The resource at ebpf-go.dev/contributing/architecture provides a good
		idea of Collection object as well as CollectionSpec object
		that is discussed here.

		This bpf2go-generated function will load compiled BPF object
		into the kernel.
	*/
	if err := LoadTracerObjects(&t.objs, nil); err != nil {
		return fmt.Errorf("syscall: load objects: %w", err)
	}

	/*
		The maps and programs have already been loaded into the kernel from
		the function above. Now we need to update the map so that the bpf
		program can do early-filtering.
	*/
	if err := t.populateFilters(); err != nil {
		return err
	}

	/*
		This function is defined in cilium/ebpf/link/tracepoint.go file. It attaches the
		given eBPF program to the tracepoint with the given group and name.

		Upon a successful call to this function, the eBPF program will start the execution
		and submit the events that was encountered within the kernel.
	*/
	lnk, err := link.Tracepoint("raw_syscalls", "sys_enter", t.objs.TraceSyscallEnter, nil)
	if err != nil {
		return fmt.Errorf("syscall: attach tracepoint: %w", err)
	}
	t.link = lnk

	/*
		Defined in cilium/ebpf/ringbuf/reader.go, this function is used to create a new BPF
		ringbuf reader.

		Note that Events is a reference to ebpf.Map type, which is defined in TracerMap
		structure. This is the same map that we defined in the eBPF file.
	*/
	rd, err := ringbuf.NewReader(t.objs.Events)
	if err != nil {
		return fmt.Errorf("syscall: open ringbuf: %w", err)
	}
	t.reader = rd

	/*
		method for BaseProgram() structure. It will simply transition to StateLoaded.
	*/
	if err := t.MarkLoaded(); err != nil {
		return err
	}

	/*
		Start reading events using the goroutine. Note that this spawns a lightweight
		"thread" managed by the runtime, and may not necessarily be an OS thread.
	*/
	go t.poll()
	return nil
}

func (t *TracerModule) Close() error {
	var errs []error

	/* ensure there are no readers */
	if t.reader != nil {
		errs = append(errs, t.reader.Close())
	}
	/* likewise, make sure we have unlinked the eBPF program as well */
	if t.link != nil {
		errs = append(errs, t.link.Close())
	}

	/*
		In our case, TracerObject structure embeds two distinct structures:
		TracerPrograms and TracerMaps. This Close() method is for the
		TracerObject data type, which internally calls the _TracerClose
		function. TracerPrograms and TracerMaps are structure with one field
		each: ebpf.Program and ebpf.Map, respectively. The generic _TracerClose
		function internally calls the Close() method for its argument. The
		structures TracerPrograms and TracerMaps do have their own Close()
		method. These Close() methods again internally calls _TracerClose
		function, which creates a chain of function calls to properly close
		BPF program or map descriptors.
	*/
	t.objs.Close()
	close(t.Events)

	/*
		MarkClosed() is a method for BaseProgram stucture. The state must
		be StateLoaded, which is updated to StateUnloaded via this call.
	*/
	if err := t.MarkClosed(); err != nil {
		errs = append(errs, err)
	}

	return exterrs.Join(errs)
}

/*
	Run consumes events from the Events channel and prints formatted
	output to stdout. It blocks until the done channel is closed (or
	the Events channel is closed). This method is intended to be called
	as a goroutine from the CLI layer.
*/
func (t *TracerModule) Run(done <-chan struct{}) {
	for {
		select {
		case e, ok := <-t.Events:
			if !ok {
				return
			}
			t.sink.Emit("syscall", syscallToFields(e))
		case <-done:
			return
		}
	}
}

/*
	syscallToFields converts a SyscallEvent into a generic field map for the
	output sink. This is the bridge between the typed event and the
	format-agnostic sink pipeline.
*/
func syscallToFields(e events.SyscallEvent) map[string]interface{} {
	return map[string]interface{}{
		"kind":       e.Kind.String(),
		"pid":        e.PID,
		"tid":        e.TID,
		"uid":        e.UID,
		"gid":        e.GID,
		"timestamp":  e.Timestamp,
		"syscall_nr": e.SyscallNr,
		"syscall":    SyscallName(e.SyscallNr),
		"comm":       e.ProcessName(),
	}
}

/*
	poll() method for TracerModule is used to read raw bytes from the ring buffer
	and converts them to events.Event. This function is called from a goroutine,
	and blocks on t.reader.Read() until data arrives.

	Userspace filters (comm name) are applied here, after parsing the event
	but before sending it to the Events channel. Kernel-side filters (PID,
	UID, syscall number) have already been applied in the BPF program.
*/
func (t *TracerModule) poll() {
	for {
		record, err := t.reader.Read()
		if err != nil {
			/* reader was closed, or some other error */
			return
		}

		/* parseEvent function is package-specific and defined in parse.go */
		e, err := parseEvent(record.RawSample)
		if err != nil {
			continue
		}

		/* Userspace filter: comm name (substring match) */
		if !t.matchesFilter(e) {
			continue
		}

		/* send the parsed message to the Events channel */
		t.Events <- e
	}
}

/*
	matchesFilter applies userspace-level filters to a parsed event.
	Returns true if the event should be forwarded to the Events channel.
	Kernel-side filters (PID, UID, syscall nr) are handled in BPF maps
	before the event reaches the ring buffer.
*/
func (t *TracerModule) matchesFilter(e events.SyscallEvent) bool {
	if t.filter.CommName != "" && !strings.Contains(e.ProcessName(), t.filter.CommName) {
		return false
	}
	return true
}
