package syscall

//go:generate bpf2go -cc clang -cflags "-O2 -g -Wall -target bpf" Tracer ../../bpf/syscall_tracer.bpf.c
//go:generate go run ../../cmd/gen/syscalls

/*
	*************** NOTE ***************

	This file relies on the existence of the ELF file that is generated via Go's
	generate subcommand. Furthermore, the second line generates the
	syscall_table.go file which is used by the CLI application. The LoadAll()
	method of BaseProgram structure internally calls the Load() method for that
	type. We define it here. Likewise, Close() method for CloseAll() method of
	BaseProgram is defined here. Do note that since we embed the BaseProgram
	structure in TracerModule, it will be compatible.

	The New() method for TracerModule object is used to allocate the storage
	which is done so by the runtime, and the poll() method is used to poll
	the goroutine till we can read from the channel.
*/

import (
	"fmt"

	"github.com/cilium/ebpf/link"
	"github.com/cilium/ebpf/ringbuf"
	"github.com/PranavRJoshi/Veil/internal/exterrs"
	"github.com/PranavRJoshi/Veil/internal/events"
	"github.com/PranavRJoshi/Veil/internal/loader"
)

/*
	A type which is compatible with the Program interface, hence the Manager type
	can contain multiple instances of this type, if ever needed.

	Both the Name() and State() methods of loader.BaseProgram are pointer receiver,
	so embedding the structure with value alone would not suffice as these methods
	would not be "promoted".
*/
type TracerModule struct {
	*loader.BaseProgram			/* embedding the BaseProgram */
	objs   TracerObjects		/* generated by bpf2go, holds maps and programs */
	link   link.Link			/* the tracepoint attachment */
	reader *ringbuf.Reader		/* reads events from the ring buffer */
	Events chan events.Event	/* userspace consumes from this channel */
}

/*
	Function which is essentially an allocator of TracerModule.
*/
func New() *TracerModule {
	return &TracerModule{
		BaseProgram: loader.NewBaseProgram("syscall_tracer"),
		Events:      make(chan events.Event, 256),
	}
}

/*
	Load() method, which is required for our Program interface.
	Note that each invocation of this function spawns a goroutine which is used
	to poll for any message written by BPF program in kernel space.
*/
func (t *TracerModule) Load() error {
	/*
		See LoadAndAssign() method of CollectionSpec for complete details.
		
		This function initially calls LoadTracer function. A new reader is
		obtained via the Reader functions defined in the bytes package.
		Next, LoadCollectionSpecFromReader from ebpf package is called with
		the Reader structure as the argument which was previously obtained. 
		This function is defined in cilium/ebpf/elf_reader.go file. The main
		functionality of this function is to convert the ELF file into
		an object of type CollectionSpec.

		One thing before moving on. The LoadCollectionSpecFromReader function
		also calls NewSafeELFFile function defined in cilium/ebpf/internal/elf.go
		file. This file imports debug/elf module which seems to contain "unfixed
		bugs", so a safe alternative needs to be implemented. Be aware that the
		safe implementation is the addition of a defer statement at the start of
		the function, where the recover() function is called. The functions: panic(),
		recover(), and defer(), are used to handle runtime errors in a gentle
		manner. By having the defer() function at the start which has the recover()
		function within it, if an error was to occur during parsing of ELF file,
		the goroutine would panic, and as libraries need to handle panics such that
		application using the library shouldn't get the panic from internal
		implementation of library, it simply catches the reason of panic through
		recover(), and returns appropriate failure condition. When no abnormal
		condition appears, recover() is simply nil and the flow is maintained.

		Finally, LoadAndAssign() method of CollectionSpec is called. This method
		is used to load maps and programs into the kernel and assigns them to
		a struct. Refer to cilium/ebpf/collection.go for actual implementation
		details.	

		The resource at ebpf-go.dev/contributing/architecture provides a good
		idea of Collection object as well as CollectionSpec object
		that is discussed here.

		This bpf2go-generated function will load compiled BPF object
		into the kernel.
	*/
	if err := LoadTracerObjects(&t.objs, nil); err != nil {
		return fmt.Errorf("syscall: load objects: %w", err)
	}

	/*
		This function is defined in cilium/ebpf/link/tracepoint.go file. It attaches the
		given eBPF program to the tracepoint with the given group and name.
	*/
	lnk, err := link.Tracepoint("raw_syscalls", "sys_enter", t.objs.TraceSyscallEnter, nil)
	if err != nil {
		return fmt.Errorf("syscall: attach tracepoint: %w", err)
	}
	t.link = lnk

	/*
		Defined in cilium/ebpf/ringbuf/reader.go, this function is used to create a new BPF
		ringbuf reader.
	*/
	rd, err := ringbuf.NewReader(t.objs.Events)
	if err != nil {
		return fmt.Errorf("syscall: open ringbuf: %w", err)
	}
	t.reader = rd

	/*
		method for BaseProgram() structure. It will simply transition to StateLoaded.
	*/
	if err := t.MarkLoaded(); err != nil {
		return err
	}

	/*
		Start reading events using the goroutine. Note that this spawns a lightweight
		"thread" managed by the runtime, and may not necessarily be an OS thread.
	*/
	go t.poll()
	return nil
}

func (t *TracerModule) Close() error {
	var errs []error

	/* ensure there are no readers */
	if t.reader != nil {
		errs = append(errs, t.reader.Close())
	}
	/* likewise, make sure we have unlinked the eBPF program as well */
	if t.link != nil {
		errs = append(errs, t.link.Close())
	}

	/*
		In our case, TracerObject structure embeds two distinct structures:
		TracerPrograms and TracerMaps. This Close() method is for the
		TracerObject data type, which internally calls the _TracerClose
		function. TracerPrograms and TracerMaps are structure with one field
		each: ebpf.Program and ebpf.Map, respectively. The generic _TracerClose
		function internally calls the Close() method for its argument. The
		structures TracerPrograms and TracerMaps do have their own Close()
		method. These Close() methods again internally calls _TracerClose
		function, which creates a chain of function calls to properly close
		BPF program or map descriptors.
	*/
	t.objs.Close()
	close(t.Events)

	/*
		MarkClosed() is a method for BaseProgram stucture. The state must
		be StateLoaded, which is updated to StateUnloaded via this call.
	*/
	if err := t.MarkClosed(); err != nil {
		errs = append(errs, err)
	}

	return exterrs.Join(errs)
}

/*
	poll() method for TracerModule is used to read raw bytes from the ring buffer
	and converts them to events.Event. This function is called from a goroutine,
	and blocks on t.reader.Read() until data arrives.
*/
func (t *TracerModule) poll() {
	for {
		record, err := t.reader.Read()
		if err != nil {
			/* reader was closed, or some other error */
			return
		}

		/* parseEvent function is package-specific and defined in parse.go */
		e, err := parseEvent(record.RawSample)
		if err != nil {
			continue
		}

		/* send the parsed message to the Events channel */
		t.Events <- e
	}
}
