// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64

package syscall

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

// LoadTracer returns the embedded CollectionSpec for Tracer.
func LoadTracer() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_TracerBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load Tracer: %w", err)
	}

	return spec, err
}

// LoadTracerObjects loads Tracer and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*TracerObjects
//	*TracerPrograms
//	*TracerMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadTracerObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := LoadTracer()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// TracerSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type TracerSpecs struct {
	TracerProgramSpecs
	TracerMapSpecs
}

// TracerSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type TracerProgramSpecs struct {
	TraceSyscallEnter *ebpf.ProgramSpec `ebpf:"trace_syscall_enter"`
}

// TracerMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type TracerMapSpecs struct {
	Events        *ebpf.MapSpec `ebpf:"events"`
	FilterCfg     *ebpf.MapSpec `ebpf:"filter_cfg"`
	PidDeny       *ebpf.MapSpec `ebpf:"pid_deny"`
	PidFilter     *ebpf.MapSpec `ebpf:"pid_filter"`
	SyscallDeny   *ebpf.MapSpec `ebpf:"syscall_deny"`
	SyscallFilter *ebpf.MapSpec `ebpf:"syscall_filter"`
	UidDeny       *ebpf.MapSpec `ebpf:"uid_deny"`
	UidFilter     *ebpf.MapSpec `ebpf:"uid_filter"`
}

// TracerObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadTracerObjects or ebpf.CollectionSpec.LoadAndAssign.
type TracerObjects struct {
	TracerPrograms
	TracerMaps
}

func (o *TracerObjects) Close() error {
	return _TracerClose(
		&o.TracerPrograms,
		&o.TracerMaps,
	)
}

// TracerMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadTracerObjects or ebpf.CollectionSpec.LoadAndAssign.
type TracerMaps struct {
	Events        *ebpf.Map `ebpf:"events"`
	FilterCfg     *ebpf.Map `ebpf:"filter_cfg"`
	PidDeny       *ebpf.Map `ebpf:"pid_deny"`
	PidFilter     *ebpf.Map `ebpf:"pid_filter"`
	SyscallDeny   *ebpf.Map `ebpf:"syscall_deny"`
	SyscallFilter *ebpf.Map `ebpf:"syscall_filter"`
	UidDeny       *ebpf.Map `ebpf:"uid_deny"`
	UidFilter     *ebpf.Map `ebpf:"uid_filter"`
}

func (m *TracerMaps) Close() error {
	return _TracerClose(
		m.Events,
		m.FilterCfg,
		m.PidDeny,
		m.PidFilter,
		m.SyscallDeny,
		m.SyscallFilter,
		m.UidDeny,
		m.UidFilter,
	)
}

// TracerPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadTracerObjects or ebpf.CollectionSpec.LoadAndAssign.
type TracerPrograms struct {
	TraceSyscallEnter *ebpf.Program `ebpf:"trace_syscall_enter"`
}

func (p *TracerPrograms) Close() error {
	return _TracerClose(
		p.TraceSyscallEnter,
	)
}

func _TracerClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//go:embed tracer_bpfel_x86.o
var _TracerBytes []byte
