// Code generated by bpf2go; DO NOT EDIT.
//go:build arm64be || armbe || mips || mips64 || mips64p32 || ppc64 || s390 || s390x || sparc || sparc64

package files

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

// LoadFileAccess returns the embedded CollectionSpec for FileAccess.
func LoadFileAccess() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_FileAccessBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load FileAccess: %w", err)
	}

	return spec, err
}

// LoadFileAccessObjects loads FileAccess and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*FileAccessObjects
//	*FileAccessPrograms
//	*FileAccessMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadFileAccessObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := LoadFileAccess()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// FileAccessSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type FileAccessSpecs struct {
	FileAccessProgramSpecs
	FileAccessMapSpecs
}

// FileAccessSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type FileAccessProgramSpecs struct {
	KprobeVfsOpen  *ebpf.ProgramSpec `ebpf:"kprobe_vfs_open"`
	KprobeVfsRead  *ebpf.ProgramSpec `ebpf:"kprobe_vfs_read"`
	KprobeVfsWrite *ebpf.ProgramSpec `ebpf:"kprobe_vfs_write"`
}

// FileAccessMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type FileAccessMapSpecs struct {
	FileEvents *ebpf.MapSpec `ebpf:"file_events"`
	FilterCfg  *ebpf.MapSpec `ebpf:"filter_cfg"`
	PidDeny    *ebpf.MapSpec `ebpf:"pid_deny"`
	PidFilter  *ebpf.MapSpec `ebpf:"pid_filter"`
	UidDeny    *ebpf.MapSpec `ebpf:"uid_deny"`
	UidFilter  *ebpf.MapSpec `ebpf:"uid_filter"`
}

// FileAccessObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadFileAccessObjects or ebpf.CollectionSpec.LoadAndAssign.
type FileAccessObjects struct {
	FileAccessPrograms
	FileAccessMaps
}

func (o *FileAccessObjects) Close() error {
	return _FileAccessClose(
		&o.FileAccessPrograms,
		&o.FileAccessMaps,
	)
}

// FileAccessMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadFileAccessObjects or ebpf.CollectionSpec.LoadAndAssign.
type FileAccessMaps struct {
	FileEvents *ebpf.Map `ebpf:"file_events"`
	FilterCfg  *ebpf.Map `ebpf:"filter_cfg"`
	PidDeny    *ebpf.Map `ebpf:"pid_deny"`
	PidFilter  *ebpf.Map `ebpf:"pid_filter"`
	UidDeny    *ebpf.Map `ebpf:"uid_deny"`
	UidFilter  *ebpf.Map `ebpf:"uid_filter"`
}

func (m *FileAccessMaps) Close() error {
	return _FileAccessClose(
		m.FileEvents,
		m.FilterCfg,
		m.PidDeny,
		m.PidFilter,
		m.UidDeny,
		m.UidFilter,
	)
}

// FileAccessPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadFileAccessObjects or ebpf.CollectionSpec.LoadAndAssign.
type FileAccessPrograms struct {
	KprobeVfsOpen  *ebpf.Program `ebpf:"kprobe_vfs_open"`
	KprobeVfsRead  *ebpf.Program `ebpf:"kprobe_vfs_read"`
	KprobeVfsWrite *ebpf.Program `ebpf:"kprobe_vfs_write"`
}

func (p *FileAccessPrograms) Close() error {
	return _FileAccessClose(
		p.KprobeVfsOpen,
		p.KprobeVfsRead,
		p.KprobeVfsWrite,
	)
}

func _FileAccessClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//go:embed fileaccess_bpfeb.o
var _FileAccessBytes []byte
