// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64

package memory

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

type MemoryTracerFaultScratch struct {
	Pid     uint32
	Tid     uint32
	Uid     uint32
	_       [4]byte
	Address uint64
	Comm    [16]uint8
}

// LoadMemoryTracer returns the embedded CollectionSpec for MemoryTracer.
func LoadMemoryTracer() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_MemoryTracerBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load MemoryTracer: %w", err)
	}

	return spec, err
}

// LoadMemoryTracerObjects loads MemoryTracer and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*MemoryTracerObjects
//	*MemoryTracerPrograms
//	*MemoryTracerMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadMemoryTracerObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := LoadMemoryTracer()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// MemoryTracerSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type MemoryTracerSpecs struct {
	MemoryTracerProgramSpecs
	MemoryTracerMapSpecs
}

// MemoryTracerSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type MemoryTracerProgramSpecs struct {
	KprobeHandleMmFault    *ebpf.ProgramSpec `ebpf:"kprobe_handle_mm_fault"`
	KretprobeHandleMmFault *ebpf.ProgramSpec `ebpf:"kretprobe_handle_mm_fault"`
}

// MemoryTracerMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type MemoryTracerMapSpecs struct {
	FaultDeny    *ebpf.MapSpec `ebpf:"fault_deny"`
	FaultFilter  *ebpf.MapSpec `ebpf:"fault_filter"`
	FaultScratch *ebpf.MapSpec `ebpf:"fault_scratch"`
	FilterCfg    *ebpf.MapSpec `ebpf:"filter_cfg"`
	MemEvents    *ebpf.MapSpec `ebpf:"mem_events"`
	PidDeny      *ebpf.MapSpec `ebpf:"pid_deny"`
	PidFilter    *ebpf.MapSpec `ebpf:"pid_filter"`
	UidDeny      *ebpf.MapSpec `ebpf:"uid_deny"`
	UidFilter    *ebpf.MapSpec `ebpf:"uid_filter"`
}

// MemoryTracerObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadMemoryTracerObjects or ebpf.CollectionSpec.LoadAndAssign.
type MemoryTracerObjects struct {
	MemoryTracerPrograms
	MemoryTracerMaps
}

func (o *MemoryTracerObjects) Close() error {
	return _MemoryTracerClose(
		&o.MemoryTracerPrograms,
		&o.MemoryTracerMaps,
	)
}

// MemoryTracerMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadMemoryTracerObjects or ebpf.CollectionSpec.LoadAndAssign.
type MemoryTracerMaps struct {
	FaultDeny    *ebpf.Map `ebpf:"fault_deny"`
	FaultFilter  *ebpf.Map `ebpf:"fault_filter"`
	FaultScratch *ebpf.Map `ebpf:"fault_scratch"`
	FilterCfg    *ebpf.Map `ebpf:"filter_cfg"`
	MemEvents    *ebpf.Map `ebpf:"mem_events"`
	PidDeny      *ebpf.Map `ebpf:"pid_deny"`
	PidFilter    *ebpf.Map `ebpf:"pid_filter"`
	UidDeny      *ebpf.Map `ebpf:"uid_deny"`
	UidFilter    *ebpf.Map `ebpf:"uid_filter"`
}

func (m *MemoryTracerMaps) Close() error {
	return _MemoryTracerClose(
		m.FaultDeny,
		m.FaultFilter,
		m.FaultScratch,
		m.FilterCfg,
		m.MemEvents,
		m.PidDeny,
		m.PidFilter,
		m.UidDeny,
		m.UidFilter,
	)
}

// MemoryTracerPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadMemoryTracerObjects or ebpf.CollectionSpec.LoadAndAssign.
type MemoryTracerPrograms struct {
	KprobeHandleMmFault    *ebpf.Program `ebpf:"kprobe_handle_mm_fault"`
	KretprobeHandleMmFault *ebpf.Program `ebpf:"kretprobe_handle_mm_fault"`
}

func (p *MemoryTracerPrograms) Close() error {
	return _MemoryTracerClose(
		p.KprobeHandleMmFault,
		p.KretprobeHandleMmFault,
	)
}

func _MemoryTracerClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//go:embed memorytracer_bpfel_x86.o
var _MemoryTracerBytes []byte
