// Code generated by bpf2go; DO NOT EDIT.
//go:build arm64

package scheduler

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

// LoadSchedulerTracer returns the embedded CollectionSpec for SchedulerTracer.
func LoadSchedulerTracer() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_SchedulerTracerBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load SchedulerTracer: %w", err)
	}

	return spec, err
}

// LoadSchedulerTracerObjects loads SchedulerTracer and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*SchedulerTracerObjects
//	*SchedulerTracerPrograms
//	*SchedulerTracerMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadSchedulerTracerObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := LoadSchedulerTracer()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// SchedulerTracerSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type SchedulerTracerSpecs struct {
	SchedulerTracerProgramSpecs
	SchedulerTracerMapSpecs
}

// SchedulerTracerSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type SchedulerTracerProgramSpecs struct {
	TraceSchedSwitch *ebpf.ProgramSpec `ebpf:"trace_sched_switch"`
}

// SchedulerTracerMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type SchedulerTracerMapSpecs struct {
	CpuDeny     *ebpf.MapSpec `ebpf:"cpu_deny"`
	CpuFilter   *ebpf.MapSpec `ebpf:"cpu_filter"`
	FilterCfg   *ebpf.MapSpec `ebpf:"filter_cfg"`
	PidDeny     *ebpf.MapSpec `ebpf:"pid_deny"`
	PidFilter   *ebpf.MapSpec `ebpf:"pid_filter"`
	SchedEvents *ebpf.MapSpec `ebpf:"sched_events"`
	UidDeny     *ebpf.MapSpec `ebpf:"uid_deny"`
	UidFilter   *ebpf.MapSpec `ebpf:"uid_filter"`
}

// SchedulerTracerObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadSchedulerTracerObjects or ebpf.CollectionSpec.LoadAndAssign.
type SchedulerTracerObjects struct {
	SchedulerTracerPrograms
	SchedulerTracerMaps
}

func (o *SchedulerTracerObjects) Close() error {
	return _SchedulerTracerClose(
		&o.SchedulerTracerPrograms,
		&o.SchedulerTracerMaps,
	)
}

// SchedulerTracerMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadSchedulerTracerObjects or ebpf.CollectionSpec.LoadAndAssign.
type SchedulerTracerMaps struct {
	CpuDeny     *ebpf.Map `ebpf:"cpu_deny"`
	CpuFilter   *ebpf.Map `ebpf:"cpu_filter"`
	FilterCfg   *ebpf.Map `ebpf:"filter_cfg"`
	PidDeny     *ebpf.Map `ebpf:"pid_deny"`
	PidFilter   *ebpf.Map `ebpf:"pid_filter"`
	SchedEvents *ebpf.Map `ebpf:"sched_events"`
	UidDeny     *ebpf.Map `ebpf:"uid_deny"`
	UidFilter   *ebpf.Map `ebpf:"uid_filter"`
}

func (m *SchedulerTracerMaps) Close() error {
	return _SchedulerTracerClose(
		m.CpuDeny,
		m.CpuFilter,
		m.FilterCfg,
		m.PidDeny,
		m.PidFilter,
		m.SchedEvents,
		m.UidDeny,
		m.UidFilter,
	)
}

// SchedulerTracerPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadSchedulerTracerObjects or ebpf.CollectionSpec.LoadAndAssign.
type SchedulerTracerPrograms struct {
	TraceSchedSwitch *ebpf.Program `ebpf:"trace_sched_switch"`
}

func (p *SchedulerTracerPrograms) Close() error {
	return _SchedulerTracerClose(
		p.TraceSchedSwitch,
	)
}

func _SchedulerTracerClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//go:embed schedulertracer_bpfel_arm64.o
var _SchedulerTracerBytes []byte
