// Code generated by bpf2go; DO NOT EDIT.
//go:build arm64

package uprobe

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

type UprobeTracerUprobeScratch struct {
	TsEnter uint64
	Pid     uint32
	Tid     uint32
	Uid     uint32
	Comm    [16]uint8
	_       [4]byte
}

// LoadUprobeTracer returns the embedded CollectionSpec for UprobeTracer.
func LoadUprobeTracer() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_UprobeTracerBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load UprobeTracer: %w", err)
	}

	return spec, err
}

// LoadUprobeTracerObjects loads UprobeTracer and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*UprobeTracerObjects
//	*UprobeTracerPrograms
//	*UprobeTracerMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadUprobeTracerObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := LoadUprobeTracer()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// UprobeTracerSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type UprobeTracerSpecs struct {
	UprobeTracerProgramSpecs
	UprobeTracerMapSpecs
}

// UprobeTracerSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type UprobeTracerProgramSpecs struct {
	UprobeEmit    *ebpf.ProgramSpec `ebpf:"uprobe_emit"`
	UprobeStore   *ebpf.ProgramSpec `ebpf:"uprobe_store"`
	UretprobeEmit *ebpf.ProgramSpec `ebpf:"uretprobe_emit"`
}

// UprobeTracerMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type UprobeTracerMapSpecs struct {
	EnterScratch *ebpf.MapSpec `ebpf:"enter_scratch"`
	FilterCfg    *ebpf.MapSpec `ebpf:"filter_cfg"`
	PidDeny      *ebpf.MapSpec `ebpf:"pid_deny"`
	PidFilter    *ebpf.MapSpec `ebpf:"pid_filter"`
	UidDeny      *ebpf.MapSpec `ebpf:"uid_deny"`
	UidFilter    *ebpf.MapSpec `ebpf:"uid_filter"`
	UprobeEvents *ebpf.MapSpec `ebpf:"uprobe_events"`
}

// UprobeTracerObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadUprobeTracerObjects or ebpf.CollectionSpec.LoadAndAssign.
type UprobeTracerObjects struct {
	UprobeTracerPrograms
	UprobeTracerMaps
}

func (o *UprobeTracerObjects) Close() error {
	return _UprobeTracerClose(
		&o.UprobeTracerPrograms,
		&o.UprobeTracerMaps,
	)
}

// UprobeTracerMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadUprobeTracerObjects or ebpf.CollectionSpec.LoadAndAssign.
type UprobeTracerMaps struct {
	EnterScratch *ebpf.Map `ebpf:"enter_scratch"`
	FilterCfg    *ebpf.Map `ebpf:"filter_cfg"`
	PidDeny      *ebpf.Map `ebpf:"pid_deny"`
	PidFilter    *ebpf.Map `ebpf:"pid_filter"`
	UidDeny      *ebpf.Map `ebpf:"uid_deny"`
	UidFilter    *ebpf.Map `ebpf:"uid_filter"`
	UprobeEvents *ebpf.Map `ebpf:"uprobe_events"`
}

func (m *UprobeTracerMaps) Close() error {
	return _UprobeTracerClose(
		m.EnterScratch,
		m.FilterCfg,
		m.PidDeny,
		m.PidFilter,
		m.UidDeny,
		m.UidFilter,
		m.UprobeEvents,
	)
}

// UprobeTracerPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadUprobeTracerObjects or ebpf.CollectionSpec.LoadAndAssign.
type UprobeTracerPrograms struct {
	UprobeEmit    *ebpf.Program `ebpf:"uprobe_emit"`
	UprobeStore   *ebpf.Program `ebpf:"uprobe_store"`
	UretprobeEmit *ebpf.Program `ebpf:"uretprobe_emit"`
}

func (p *UprobeTracerPrograms) Close() error {
	return _UprobeTracerClose(
		p.UprobeEmit,
		p.UprobeStore,
		p.UretprobeEmit,
	)
}

func _UprobeTracerClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//go:embed uprobetracer_bpfel_arm64.o
var _UprobeTracerBytes []byte
