// Code generated by bpf2go; DO NOT EDIT.
//go:build arm64

package network

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

type NetworkTracerPidInfo struct {
	Pid  uint32
	Uid  uint32
	Comm [16]uint8
}

// LoadNetworkTracer returns the embedded CollectionSpec for NetworkTracer.
func LoadNetworkTracer() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_NetworkTracerBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load NetworkTracer: %w", err)
	}

	return spec, err
}

// LoadNetworkTracerObjects loads NetworkTracer and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*NetworkTracerObjects
//	*NetworkTracerPrograms
//	*NetworkTracerMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadNetworkTracerObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := LoadNetworkTracer()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// NetworkTracerSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type NetworkTracerSpecs struct {
	NetworkTracerProgramSpecs
	NetworkTracerMapSpecs
}

// NetworkTracerSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type NetworkTracerProgramSpecs struct {
	HandleInetSockSetState *ebpf.ProgramSpec `ebpf:"handle_inet_sock_set_state"`
	KprobeInetListen       *ebpf.ProgramSpec `ebpf:"kprobe_inet_listen"`
	KprobeTcpV4Connect     *ebpf.ProgramSpec `ebpf:"kprobe_tcp_v4_connect"`
	KretprobeInetCskAccept *ebpf.ProgramSpec `ebpf:"kretprobe_inet_csk_accept"`
}

// NetworkTracerMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type NetworkTracerMapSpecs struct {
	FilterCfg  *ebpf.MapSpec `ebpf:"filter_cfg"`
	ListenPid  *ebpf.MapSpec `ebpf:"listen_pid"`
	NetEvents  *ebpf.MapSpec `ebpf:"net_events"`
	PidDeny    *ebpf.MapSpec `ebpf:"pid_deny"`
	PidFilter  *ebpf.MapSpec `ebpf:"pid_filter"`
	PortDeny   *ebpf.MapSpec `ebpf:"port_deny"`
	PortFilter *ebpf.MapSpec `ebpf:"port_filter"`
	SockPid    *ebpf.MapSpec `ebpf:"sock_pid"`
	UidDeny    *ebpf.MapSpec `ebpf:"uid_deny"`
	UidFilter  *ebpf.MapSpec `ebpf:"uid_filter"`
}

// NetworkTracerObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadNetworkTracerObjects or ebpf.CollectionSpec.LoadAndAssign.
type NetworkTracerObjects struct {
	NetworkTracerPrograms
	NetworkTracerMaps
}

func (o *NetworkTracerObjects) Close() error {
	return _NetworkTracerClose(
		&o.NetworkTracerPrograms,
		&o.NetworkTracerMaps,
	)
}

// NetworkTracerMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadNetworkTracerObjects or ebpf.CollectionSpec.LoadAndAssign.
type NetworkTracerMaps struct {
	FilterCfg  *ebpf.Map `ebpf:"filter_cfg"`
	ListenPid  *ebpf.Map `ebpf:"listen_pid"`
	NetEvents  *ebpf.Map `ebpf:"net_events"`
	PidDeny    *ebpf.Map `ebpf:"pid_deny"`
	PidFilter  *ebpf.Map `ebpf:"pid_filter"`
	PortDeny   *ebpf.Map `ebpf:"port_deny"`
	PortFilter *ebpf.Map `ebpf:"port_filter"`
	SockPid    *ebpf.Map `ebpf:"sock_pid"`
	UidDeny    *ebpf.Map `ebpf:"uid_deny"`
	UidFilter  *ebpf.Map `ebpf:"uid_filter"`
}

func (m *NetworkTracerMaps) Close() error {
	return _NetworkTracerClose(
		m.FilterCfg,
		m.ListenPid,
		m.NetEvents,
		m.PidDeny,
		m.PidFilter,
		m.PortDeny,
		m.PortFilter,
		m.SockPid,
		m.UidDeny,
		m.UidFilter,
	)
}

// NetworkTracerPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadNetworkTracerObjects or ebpf.CollectionSpec.LoadAndAssign.
type NetworkTracerPrograms struct {
	HandleInetSockSetState *ebpf.Program `ebpf:"handle_inet_sock_set_state"`
	KprobeInetListen       *ebpf.Program `ebpf:"kprobe_inet_listen"`
	KprobeTcpV4Connect     *ebpf.Program `ebpf:"kprobe_tcp_v4_connect"`
	KretprobeInetCskAccept *ebpf.Program `ebpf:"kretprobe_inet_csk_accept"`
}

func (p *NetworkTracerPrograms) Close() error {
	return _NetworkTracerClose(
		p.HandleInetSockSetState,
		p.KprobeInetListen,
		p.KprobeTcpV4Connect,
		p.KretprobeInetCskAccept,
	)
}

func _NetworkTracerClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//go:embed networktracer_bpfel_arm64.o
var _NetworkTracerBytes []byte
